# Generated by Django 4.2.12 on 2024-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery_personnel', 'Delivery Personnel'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
