# Generated by Django 4.2.12 on 2024-09-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_delivery_personnel', to='grocery.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to='grocery.profile'),
        ),
    ]
