# Generated by Django 4.2.12 on 2024-09-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_order_delivery_personnel_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_personnel_orders', to='grocery.profile'),
        ),
    ]
