# Generated by Django 4.2.12 on 2024-09-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_alter_order_customer_alter_order_delivery_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='grocery.product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.profile')),
            ],
        ),
    ]
