# Generated by Django 4.2.12 on 2024-09-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Product',
            new_name='product',
        ),
    ]
