# Generated by Django 4.2.12 on 2024-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_rename_product_vendor_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
