# Generated by Django 4.2.12 on 2024-09-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_vendor_email_vendor_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': [('can_manage_business', 'Can manage their business'), ('can_edit_own_profile', 'Can edit own profile'), ('can_view_own_profile', 'Can view own profile')]},
        ),
    ]
