# Generated by Django 4.2.12 on 2024-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_alter_vendor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='no category provided', max_length=100),
        ),
    ]
