# Generated by Django 4.2.12 on 2024-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
