# Generated by Django 4.2.12 on 2024-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0019_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
