# Generated by Django 4.2.12 on 2024-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_alter_order_vendor_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=20),
        ),
    ]
