# Generated by Django 4.2.12 on 2024-09-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0027_category_remove_cart_customer_remove_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='grocery_subcategory',
        ),
    ]
