# Generated by Django 4.2.12 on 2024-09-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0030_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
