# Generated by Django 4.2.12 on 2024-09-13 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0032_alter_order_ordered_at_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_date',
            new_name='delivered_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='grocery.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
