# Generated by Django 4.2.12 on 2024-09-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0039_alter_order_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product',
        ),
    ]
