# Generated by Django 4.2.12 on 2024-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0040_remove_vendor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
