# Generated by Django 4.2.12 on 2024-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0047_remove_cart_user_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
