# Generated by Django 4.2.12 on 2024-09-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0048_profile_email_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
