# Generated by Django 4.2.12 on 2024-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0053_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_history',
            field=models.JSONField(default=list),
        ),
    ]
