# Generated by Django 4.2.12 on 2024-09-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0054_order_status_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_history',
        ),
    ]
