# Generated by Django 4.2.12 on 2024-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0058_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
