# Generated by Django 5.1.1 on 2024-09-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0062_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
    ]
