# Generated by Django 5.1.1 on 2024-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0065_alter_order_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery_personnel', 'Delivery Personnel'), ('customer', 'Customer')], max_length=50),
        ),
    ]
