# Generated by Django 5.1.1 on 2024-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0066_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery_personnel', 'Delivery Personnel'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
