# Generated by Django 5.1.1 on 2024-10-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0069_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Manager', 'Manager')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.profile')),
            ],
            options={
                'permissions': [('can_manage_system', 'Can manage the system'), ('can_edit_own_profile', 'Can edit own profile')],
            },
        ),
    ]
