# Generated by Django 5.1.1 on 2024-10-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0071_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.order'),
        ),
    ]
