# Generated by Django 5.1.1 on 2024-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0072_useractivity_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
