# Generated by Django 5.1.1 on 2024-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0074_alter_order_ordered_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='SalesReport',
        ),
    ]
