# Generated by Django 5.1.1 on 2024-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0075_rename_sale_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
