# Generated by Django 5.1.1 on 2024-10-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0076_alter_salesreport_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonnel',
            name='assigned_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='max_daily_assignments',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Placed', max_length=20),
        ),
    ]
